import type { Metadata } from "next"
import { Inconsolata } from "next/font/google"
import "./globals.css"

const inconsolata = Inconsolata({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Code Hike v1 Starter",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="dark prose prose-invert mx-auto max-w-5xl bg-zinc-950 px-4 py-24"
    >
      <body className={inconsolata.className}>{children}</body>
    </html>
  )
}
